export default [
  {
    id: Math.random(),
    name: "Blinking Reminder",
    desc : "Blinking Reminder Desc",
    noOfTime: "always",
    intervalPeriod: 20,
    completedCycle: 0,
    isSnooze: true,
  },
  {
    id: Math.random(),
    name: "Water Reminder",
    desc : "Water Reminder Desc",
    noOfTime: "always",
    intervalPeriod: 45,
    completedCycle: 0,
    isSnooze: true,
  },
  {
    id: Math.random(),
    name: "Stretch Reminder",
    desc : "Stretch Reminder Desc",
    noOfTime: "always",
    intervalPeriod: 60,
    completedCycle: 0,
    isSnooze: true,
  },
  {
    id: Math.random(),
    name: "Posture Reminder",
    desc : "Posture Reminder Desc",
    noOfTime: "always",
    intervalPeriod: 20,
    completedCycle: 0,
    isSnooze: true,
  },
];
