export default [
  {
    id: Math.random(),
    name: "Sit up straight",
    desc : "Once more the Sit will rule the galaxy!",
    noOfTime: "always",
    intervalPeriod: 15,
    completedCycle: 0,
    isSnooze: true,
  },
  {
    id: Math.random(),
    name: "Hydrate yourself",
    desc : "Feel the Water around you.",
    noOfTime: "always",
    intervalPeriod: 30,
    completedCycle: 0,
    isSnooze: true,
  },
  {
    id: Math.random(),
    name: "Rest your eyes",
    desc : "See through the lies of the Jedi.",
    noOfTime: "always",
    intervalPeriod: 30,
    completedCycle: 0,
    isSnooze: true,
  },
  {
    id: Math.random(),
    name: "Stretch your legs",
    desc : "Your path you must decide, young Walker.",
    noOfTime: "always",
    intervalPeriod: 60,
    completedCycle: 0,
    isSnooze: true,
  },
];
